### ISSUE TITLE
Dependency convergence issue

### ISSUE THREAD

**Issue by X3Cutor** [yunspace/dropwizard-xml#4]
Hi

Using maven and Dropwizard 0.7.1 I get a massive dependency convergence issue which I think boils down to that Dropwizard uses jackson 2.3.3 and dropwizard-xml according to the maven 0.7.1-2 uses a 2.4.3 dependency:
    <dependency>
      <groupId>com.fasterxml.jackson.jaxrs</groupId>
      <artifactId>jackson-jaxrs-xml-provider</artifactId>
      <version>2.4.3</version>
      <scope>runtime</scope>
    </dependency>

**Comment by yunspace** [comment]
I've modified the Jackson version to be 2.3.3, and downgraded woodstox and stax2 to be 4.4.1 and 3.1.4 respectively. Let me know if you come across any more issues.
